version: '3.8'

services:
  # Frontend
  gym_frontend:
    container_name: gym_frontend
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    networks:
      - gym_cms_network
    depends_on:
      - gym_cms
    volumes:
      - ./frontend/src/:/app/src/
    environment:
      NODE_ENV: ${ENV_TYPE}

  # CMS
  gym_cms:
    container_name: gym_cms
    restart: unless-stopped
    build:
      context: ./cms
      dockerfile: Dockerfile
    environment:
      HOST: ${CMS_HOST}
      PORT: ${CMS_DATABASE_PORT}
      NODE_ENV: ${ENV_TYPE}
      DATABASE_HOST: ${CMS_DATABASE_HOST}
      DATABASE_NAME: ${CMS_DATABASE_NAME}
      DATABASE_USERNAME: ${CMS_DATABASE_USERNAME}
      DATABASE_PASSWORD: ${CMS_DATABASE_PASSWORD}
    ports:
      - 1337:1337
    networks:
      - gym_cms_network
    depends_on:
      - gym_datastore
    volumes:
      - ./cms/api/:/app/api/
      - ./cms/config/:/app/config/
      - ./cms/extensions/:/app/extensions/

  # CMS Datastore
  gym_datastore:
    image: mongo
    container_name: gym_datastore
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: ${CMS_DATABASE_NAME}
      MONGO_INITDB_ROOT_USERNAME: ${CMS_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${CMS_INITDB_ROOT_PASSWORD}
    networks:
      - gym_cms_network
    expose:
      - 27017
    volumes:
      - cmsdata:/data/db

networks:
  gym_cms_network:
    driver: bridge

volumes:
  cmsdata:
